name: Crawling Google Play Store Reviews

on: push

jobs:
  crawl_reviews:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six
        pip install requests
        pip install google_play_scraper
        pip install app-store-scraper
        pip install --upgrade --user urllib3
        pip install --upgrade --user six

    - name: Verify installed packages
      run: |
        pip show six
        pip show requests
        pip show google_play_scraper
        pip show app-store-scraper

    - name: Run crawler script
      run: python crawler.py 
      env:
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}